### ISSUE TITLE
Osetrit InformUserException

### ISSUE THREAD

**Issue by jkbmat** [matragorn/PV138_RSS_reader#13]

**Comment by jkbmat** [comment]
Pridal som InformUserException, cez ktoru sa budu riesit chybove hlasky. Treba dat try/catch, ktory v pripade InformUserException vyhodi okno s chybovou hlaskou v e.message, minimalne ku:
- button Prihlasit novy odber (staci zmenit preddefinovanu chybovu hlasku na e.message)
- button Pridat kanal v sprave kategorii

**Comment by matragorn** [comment]
hotovo
