### ISSUE TITLE
Lokalizace

### ISSUE THREAD

**Issue by matragorn** [matragorn/PV138_RSS_reader#2]
Aplikace je zatím napůl anglicky a napůl česky měli bychom se rozhodnout pro jeden jazyk a poté by to někdo měl lokalizovat.

já hlasuju pro Češtinu

**Comment by JirkaVrbka** [comment]
to zni dobre

**Comment by lukasFindura** [comment]
Čeština je ok

**Comment by matragorn** [comment]
Ok, uzavirám problém s tím že aplikaci plně lokalizuji do CZE
