### ISSUE TITLE
Nastavit clanok ako precitany hned po kliknuti

### ISSUE THREAD

**Issue by jkbmat** [matragorn/PV138_RSS_reader#3]
Navrhujem odstranit delay medzi kliknutim na clanok a jeho nastavenim ako precitany. Pouziva sa to dost zvlastne a ani v inych citackach som to este nevidel.  Zaroven potrebujeme tlacitko ktore prehadzuje stav medzi precitany/neprecitany, ktore by fungovalo aj pri vybere viacerych clankov.

**Comment by matragorn** [comment]
ok, toto hování sem odkoukal z outlooku, kde si prolikavas e-maily a ctes je podle zajimavosti a nechces aby hned po kliknuti byly prectene i ty co si ve zkutecnosti necetl, ale u e-mailu chces číst vše a ma to asi větsi opodstatnění... ten delay zmenším na 0,5 sec jak jsme se bavili a tlačitko přidám.

**Comment by lukasFindura** [comment]
potom by som tú pol sekundu ešte vyskúšal v praxi, lebo mám také tušenie, že aj keď sa niekto "uklikne" tak za tú pol sekundu sa nestihne prekliknúť do správneho articlu.

**Comment by matragorn** [comment]
vyzkoušej v praxi, je to jedna konstanta, ted float, da se to menit behem vteřiny :-)

**Comment by jkbmat** [comment]
Po vyskusani za mna navrhujem zrusit, robi to dojem neresponzivnosti

**Comment by matragorn** [comment]
nejsem proti, co lukas?

**Comment by lukasFindura** [comment]
ja súhlasím

**Comment by matragorn** [comment]
hotovo
