### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by matragorn** [matragorn/PV138_RSS_reader#5]
Exeption vniká pri kliku na prázdnou kategorii - snaží se asi načíst null

![image](https://cloud.githubusercontent.com/assets/12081871/7847034/869be6e0-04c1-11e5-8e3d-8475c3dd907e.png)

**Comment by jkbmat** [comment]
Je to issue na GUI, ŽÁDNÉ FEEDY ma priradeny null Tag a zaroven sa pri kliknuti na to snazi vypisat clanky podla Tagu.

**Comment by jkbmat** [comment]
Exception vznika koli riadku 324 vo Form1.cs:
`actuallyShowingArticles = (manager.Articles((Feed)e.Node.Tag)).Where(x => x.Starred).ToList();`

**Comment by matragorn** [comment]
done
