### ISSUE TITLE
V hlavnom okne nejde menit sirku laveho panelu

### ISSUE THREAD

**Issue by jkbmat** [matragorn/PV138_RSS_reader#7]
Z testu to vyzera tak, ze ma nastaveny nejaky rozsah min-max sirky (kde max je ale mensie ako defaultna hodnota). Navrhujem neobmedzovat zhora.

Podobne sa sprava aj slider medzi zoznamom clankov a vypisom clanku (ale bez max/default konfliktu):
![image](https://cloud.githubusercontent.com/assets/12083493/7855481/610bf7ec-0522-11e5-8de5-aab6a5eb63fb.png)
Toto je najviac posunute v prospech zoznamu clankov. Na velkom monitore to, myslim, nestaci.

**Comment by matragorn** [comment]
tohle řeší konstanty 

```
    private const int TREE_PANEL_MAX_WIDTH = 250;
    private const int TREE_PANEL_MIN_WIDTH = 150;
    private const int FEEDS_PANEL_MAX_WIDTH = 400;
    private const int FEEDS_PANEL_MIN_WIDTH = 150;
```

jak je nastavíme lépe?

**Comment by jkbmat** [comment]
Obidva max ked sa nastavia na 1000 je to fajn

**Comment by matragorn** [comment]
tak sem to nastavil
